language: csharp
script:
  - nuget restore SuperSocket-Net40.sln
  - xbuild SuperSocket-Net40.sln
  - nuget restore SuperSocket-Net45.sln
  - xbuild SuperSocket-Net45.sln
  - xbuild SuperSocket.Portable.sln
