name: build

on:
    push:
        branches:
            - master
            - 2refactory

jobs:
    build:
        strategy:
          matrix:
            os:
              - ubuntu-latest
              - windows-latest
              - macos-latest
        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            - name: Set env
              run: |
                echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
                echo "DOTNET_hostBuilder:reloadConfigOnChange=false" >> $GITHUB_ENV
            - name: Clean
              run: |
                dotnet clean ./SuperSocket.sln --configuration Release
                dotnet clean ./samples/samples.sln --configuration Release
                dotnet nuget locals all --clear
            - name: Build
              run: dotnet build -c Release
            - name: Build Samples
              run: dotnet build -c Release samples/samples.sln
            - name: Test
              run: |
                cd test/SuperSocket.Tests
                dotnet test