name: myget-release
on: [workflow_dispatch]
jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            - name: Set env
              run: echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Pack
              run: dotnet pack -c Release -p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }} -p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }} -p:AssemblyVersion=${{ steps.nbgv.outputs.AssemblyVersion }} -p:AssemblyFileVersion=${{ steps.nbgv.outputs.AssemblyFileVersion }} -p:AssemblyInformationalVersion=${{ steps.nbgv.outputs.AssemblyInformationalVersion }} /p:NoPackageAnalysis=true
            - name: Pack all-in-one-packages
              run:  |
                dotnet pack -c Release -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}" pkg/SuperSocket.csproj
            - name: Push
              run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/supersocket/api/v3/index.json
