name: myget-release
on: [workflow_dispatch]
jobs:
    push:
        runs-on: ubuntu-latest
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.1.401
            - name: Pack
              run: dotnet pack -c Release
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Pack all-in-one-packages
              run:  |
                dotnet pack -c Release -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}" pkg/SuperSocket.csproj
                dotnet pack -c Release -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}" pkg/SuperSocket.WebSocketServer.csproj 
            - name: Push
              run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/supersocket/api/v3/index.json
