name: myget

on:
    push:
        branches:
            - master

jobs:
    push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: 3.1.401
            - name: Set env
              run: echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Pack
              run: dotnet pack -c Release /p:PublicRelease=false -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }}" pkg/SuperSocket.csproj
            - uses: dotnet/nbgv@master
              id: nbgv
            - name: Pack all-in-one-packages
              run:  |
                dotnet pack -c Release -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }}" pkg/SuperSocket.csproj
                dotnet pack -c Release -p:NuspecProperties="version=${{ steps.nbgv.outputs.NuGetPackageVersion }}.${{ github.run_number }}" pkg/SuperSocket.WebSocketServer.csproj 
            - name: Push
              run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --source https://www.myget.org/F/supersocket/api/v3/index.json
